[package]
name = "bitatom"
version = "0.1.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.31.1", features = ["std", "rand", "hashes"] }
hex = "0.4.3"
rand = { version = "0.9.2" }
zeroize = { version = "1.8.2", features = ["zeroize_derive"] }
once_cell = "1.10.0"
